'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace WSSimple
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WSSimple.ServicioWebSimpleSoap")>  _
    Public Interface ServicioWebSimpleSoap
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Hola_mundoResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Hola_mundo", ReplyAction:="*")>  _
        Function Hola_mundo(ByVal request As WSSimple.Hola_mundoRequest) As WSSimple.Hola_mundoResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Hola_mundo", ReplyAction:="*")>  _
        Function Hola_mundoAsync(ByVal request As WSSimple.Hola_mundoRequest) As System.Threading.Tasks.Task(Of WSSimple.Hola_mundoResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/HolaMasNombre", ReplyAction:="*")>  _
        Function HolaMasNombre(ByVal request As WSSimple.HolaMasNombreRequest) As WSSimple.HolaMasNombreResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/HolaMasNombre", ReplyAction:="*")>  _
        Function HolaMasNombreAsync(ByVal request As WSSimple.HolaMasNombreRequest) As System.Threading.Tasks.Task(Of WSSimple.HolaMasNombreResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Fecha_y_HoraResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Fecha_y_Hora", ReplyAction:="*")>  _
        Function Fecha_y_Hora(ByVal request As WSSimple.Fecha_y_HoraRequest) As WSSimple.Fecha_y_HoraResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Fecha_y_Hora", ReplyAction:="*")>  _
        Function Fecha_y_HoraAsync(ByVal request As WSSimple.Fecha_y_HoraRequest) As System.Threading.Tasks.Task(Of WSSimple.Fecha_y_HoraResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Suma", ReplyAction:="*")>  _
        Function Suma(ByVal Primer_numero As Integer, ByVal Segundo_numero As Integer) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Suma", ReplyAction:="*")>  _
        Function SumaAsync(ByVal Primer_numero As Integer, ByVal Segundo_numero As Integer) As System.Threading.Tasks.Task(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Resta", ReplyAction:="*")>  _
        Function Resta(ByVal Primer_numero As Integer, ByVal Segundo_numero As Integer) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Resta", ReplyAction:="*")>  _
        Function RestaAsync(ByVal Primer_numero As Integer, ByVal Segundo_numero As Integer) As System.Threading.Tasks.Task(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Multiplicacion", ReplyAction:="*")>  _
        Function Multiplicacion(ByVal Primer_numero As Integer, ByVal Segundo_numero As Integer) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Multiplicacion", ReplyAction:="*")>  _
        Function MultiplicacionAsync(ByVal Primer_numero As Integer, ByVal Segundo_numero As Integer) As System.Threading.Tasks.Task(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Division", ReplyAction:="*")>  _
        Function Division(ByVal Primer_numero As Double, ByVal Segundo_numero As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Division", ReplyAction:="*")>  _
        Function DivisionAsync(ByVal Primer_numero As Double, ByVal Segundo_numero As Double) As System.Threading.Tasks.Task(Of Double)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Hola_mundoRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Hola_mundo", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSSimple.Hola_mundoRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSSimple.Hola_mundoRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class Hola_mundoRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Hola_mundoResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Hola_mundoResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSSimple.Hola_mundoResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSSimple.Hola_mundoResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Hola_mundoResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Hola_mundoResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Hola_mundoResult As String)
            MyBase.New
            Me.Hola_mundoResult = Hola_mundoResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class HolaMasNombreRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="HolaMasNombre", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSSimple.HolaMasNombreRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSSimple.HolaMasNombreRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class HolaMasNombreRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Nombre As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Nombre As String)
            MyBase.New
            Me.Nombre = Nombre
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class HolaMasNombreResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="HolaMasNombreResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSSimple.HolaMasNombreResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSSimple.HolaMasNombreResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class HolaMasNombreResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public HolaMasNombreResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal HolaMasNombreResult As String)
            MyBase.New
            Me.HolaMasNombreResult = HolaMasNombreResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Fecha_y_HoraRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Fecha_y_Hora", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSSimple.Fecha_y_HoraRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSSimple.Fecha_y_HoraRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class Fecha_y_HoraRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Fecha_y_HoraResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Fecha_y_HoraResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSSimple.Fecha_y_HoraResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSSimple.Fecha_y_HoraResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Fecha_y_HoraResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Fecha_y_HoraResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Fecha_y_HoraResult As String)
            MyBase.New
            Me.Fecha_y_HoraResult = Fecha_y_HoraResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ServicioWebSimpleSoapChannel
        Inherits WSSimple.ServicioWebSimpleSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ServicioWebSimpleSoapClient
        Inherits System.ServiceModel.ClientBase(Of WSSimple.ServicioWebSimpleSoap)
        Implements WSSimple.ServicioWebSimpleSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSSimple_ServicioWebSimpleSoap_Hola_mundo(ByVal request As WSSimple.Hola_mundoRequest) As WSSimple.Hola_mundoResponse Implements WSSimple.ServicioWebSimpleSoap.Hola_mundo
            Return MyBase.Channel.Hola_mundo(request)
        End Function
        
        Public Function Hola_mundo() As String
            Dim inValue As WSSimple.Hola_mundoRequest = New WSSimple.Hola_mundoRequest()
            inValue.Body = New WSSimple.Hola_mundoRequestBody()
            Dim retVal As WSSimple.Hola_mundoResponse = CType(Me,WSSimple.ServicioWebSimpleSoap).Hola_mundo(inValue)
            Return retVal.Body.Hola_mundoResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSSimple_ServicioWebSimpleSoap_Hola_mundoAsync(ByVal request As WSSimple.Hola_mundoRequest) As System.Threading.Tasks.Task(Of WSSimple.Hola_mundoResponse) Implements WSSimple.ServicioWebSimpleSoap.Hola_mundoAsync
            Return MyBase.Channel.Hola_mundoAsync(request)
        End Function
        
        Public Function Hola_mundoAsync() As System.Threading.Tasks.Task(Of WSSimple.Hola_mundoResponse)
            Dim inValue As WSSimple.Hola_mundoRequest = New WSSimple.Hola_mundoRequest()
            inValue.Body = New WSSimple.Hola_mundoRequestBody()
            Return CType(Me,WSSimple.ServicioWebSimpleSoap).Hola_mundoAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSSimple_ServicioWebSimpleSoap_HolaMasNombre(ByVal request As WSSimple.HolaMasNombreRequest) As WSSimple.HolaMasNombreResponse Implements WSSimple.ServicioWebSimpleSoap.HolaMasNombre
            Return MyBase.Channel.HolaMasNombre(request)
        End Function
        
        Public Function HolaMasNombre(ByVal Nombre As String) As String
            Dim inValue As WSSimple.HolaMasNombreRequest = New WSSimple.HolaMasNombreRequest()
            inValue.Body = New WSSimple.HolaMasNombreRequestBody()
            inValue.Body.Nombre = Nombre
            Dim retVal As WSSimple.HolaMasNombreResponse = CType(Me,WSSimple.ServicioWebSimpleSoap).HolaMasNombre(inValue)
            Return retVal.Body.HolaMasNombreResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSSimple_ServicioWebSimpleSoap_HolaMasNombreAsync(ByVal request As WSSimple.HolaMasNombreRequest) As System.Threading.Tasks.Task(Of WSSimple.HolaMasNombreResponse) Implements WSSimple.ServicioWebSimpleSoap.HolaMasNombreAsync
            Return MyBase.Channel.HolaMasNombreAsync(request)
        End Function
        
        Public Function HolaMasNombreAsync(ByVal Nombre As String) As System.Threading.Tasks.Task(Of WSSimple.HolaMasNombreResponse)
            Dim inValue As WSSimple.HolaMasNombreRequest = New WSSimple.HolaMasNombreRequest()
            inValue.Body = New WSSimple.HolaMasNombreRequestBody()
            inValue.Body.Nombre = Nombre
            Return CType(Me,WSSimple.ServicioWebSimpleSoap).HolaMasNombreAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSSimple_ServicioWebSimpleSoap_Fecha_y_Hora(ByVal request As WSSimple.Fecha_y_HoraRequest) As WSSimple.Fecha_y_HoraResponse Implements WSSimple.ServicioWebSimpleSoap.Fecha_y_Hora
            Return MyBase.Channel.Fecha_y_Hora(request)
        End Function
        
        Public Function Fecha_y_Hora() As String
            Dim inValue As WSSimple.Fecha_y_HoraRequest = New WSSimple.Fecha_y_HoraRequest()
            inValue.Body = New WSSimple.Fecha_y_HoraRequestBody()
            Dim retVal As WSSimple.Fecha_y_HoraResponse = CType(Me,WSSimple.ServicioWebSimpleSoap).Fecha_y_Hora(inValue)
            Return retVal.Body.Fecha_y_HoraResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSSimple_ServicioWebSimpleSoap_Fecha_y_HoraAsync(ByVal request As WSSimple.Fecha_y_HoraRequest) As System.Threading.Tasks.Task(Of WSSimple.Fecha_y_HoraResponse) Implements WSSimple.ServicioWebSimpleSoap.Fecha_y_HoraAsync
            Return MyBase.Channel.Fecha_y_HoraAsync(request)
        End Function
        
        Public Function Fecha_y_HoraAsync() As System.Threading.Tasks.Task(Of WSSimple.Fecha_y_HoraResponse)
            Dim inValue As WSSimple.Fecha_y_HoraRequest = New WSSimple.Fecha_y_HoraRequest()
            inValue.Body = New WSSimple.Fecha_y_HoraRequestBody()
            Return CType(Me,WSSimple.ServicioWebSimpleSoap).Fecha_y_HoraAsync(inValue)
        End Function

        Public Function Suma(ByVal Primer_numero As Integer, ByVal Segundo_numero As Integer) As Integer Implements WSSimple.ServicioWebSimpleSoap.Suma
            Return MyBase.Channel.Suma(Primer_numero, Segundo_numero)
        End Function

        Public Function SumaAsync(ByVal Primer_numero As Integer, ByVal Segundo_numero As Integer) As System.Threading.Tasks.Task(Of Integer) Implements WSSimple.ServicioWebSimpleSoap.SumaAsync
            Return MyBase.Channel.SumaAsync(Primer_numero, Segundo_numero)
        End Function
        
        Public Function Resta(ByVal Primer_numero As Integer, ByVal Segundo_numero As Integer) As Integer Implements WSSimple.ServicioWebSimpleSoap.Resta
            Return MyBase.Channel.Resta(Primer_numero, Segundo_numero)
        End Function
        
        Public Function RestaAsync(ByVal Primer_numero As Integer, ByVal Segundo_numero As Integer) As System.Threading.Tasks.Task(Of Integer) Implements WSSimple.ServicioWebSimpleSoap.RestaAsync
            Return MyBase.Channel.RestaAsync(Primer_numero, Segundo_numero)
        End Function
        
        Public Function Multiplicacion(ByVal Primer_numero As Integer, ByVal Segundo_numero As Integer) As Integer Implements WSSimple.ServicioWebSimpleSoap.Multiplicacion
            Return MyBase.Channel.Multiplicacion(Primer_numero, Segundo_numero)
        End Function
        
        Public Function MultiplicacionAsync(ByVal Primer_numero As Integer, ByVal Segundo_numero As Integer) As System.Threading.Tasks.Task(Of Integer) Implements WSSimple.ServicioWebSimpleSoap.MultiplicacionAsync
            Return MyBase.Channel.MultiplicacionAsync(Primer_numero, Segundo_numero)
        End Function
        
        Public Function Division(ByVal Primer_numero As Double, ByVal Segundo_numero As Double) As Double Implements WSSimple.ServicioWebSimpleSoap.Division
            Return MyBase.Channel.Division(Primer_numero, Segundo_numero)
        End Function
        
        Public Function DivisionAsync(ByVal Primer_numero As Double, ByVal Segundo_numero As Double) As System.Threading.Tasks.Task(Of Double) Implements WSSimple.ServicioWebSimpleSoap.DivisionAsync
            Return MyBase.Channel.DivisionAsync(Primer_numero, Segundo_numero)
        End Function
    End Class
End Namespace
